LIB_SRC = 			\
	Acceptor.cpp	\
	Channel.cpp		\
	EventLoop.cpp	\
	EventLoopThread.cpp		\
	InetAddress.cpp			\
	Poller.cpp		\
	Socket.cpp		\
	SocketsOps.cpp			\
	Timer.cpp		\
	TimerQueue.cpp			\

BINARIES = test7

all: $(BINARIES)

include ../reactor.mk

test7: test7.cpp