LIB_SRC = Channel.cpp EventLoop.cpp Poller.cpp Timer.cpp TimerQueue.cpp
BINARIES = test1 test2 test3 test4

all: $(BINARIES)

include ../reactor.mk

test1: test1.cpp
test2: test2.cpp
test3: test3.cpp
test4: test4.cpp