LIB_SRC = 			\
	Acceptor.cpp	\
	Buffer.cpp		\
	Channel.cpp		\
	EventLoop.cpp	\
	EventLoopThread.cpp		\
	InetAddress.cpp			\
	Poller.cpp		\
	Socket.cpp		\
	SocketsOps.cpp			\
	TcpConnection.cpp		\
	TcpServer.cpp			\
	Timer.cpp		\
	TimerQueue.cpp			\

BINARIES = test9 test10

all: $(BINARIES)

include ../reactor.mk

test9: test9.cpp
test10: test10.cpp